services:
  postgresql:
    image: postgres:14
    container_name: pythonApp
    ports:
      - 5433:5433
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cocoro
      POSTGRES_PASSWORD: Pa55word
      POSTGRES_DB: test_python
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    hostname: postgres
    restart: always
    user: root

volumes:
  db_data: {}
