services:
  postgresql:
    image: postgres:14
    container_name: pythonApp
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cocoro
      POSTGRES_PASSWORD: Pa55word
      POSTGRES_DB: pydb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: cocoro@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgresql

volumes:
  db_data: {}