"""test1

Revision ID: 11b04bf5a583
Revises: 
Create Date: 2025-01-27 18:09:43.891443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b04bf5a583'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ExerciseResult_id'), 'ExerciseResult', ['id'], unique=False)
    op.drop_constraint('ExerciseResult_user_id_fkey', 'ExerciseResult', type_='foreignkey')
    op.drop_column('ExerciseResult', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExerciseResult', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ExerciseResult_user_id_fkey', 'ExerciseResult', 'User', ['user_id'], ['id'])
    op.drop_index(op.f('ix_ExerciseResult_id'), table_name='ExerciseResult')
    # ### end Alembic commands ###
