"""test1

Revision ID: 3f7ce90bdb84
Revises: 105cbfba2775
Create Date: 2025-01-27 18:10:38.594684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7ce90bdb84'
down_revision: Union[str, None] = '105cbfba2775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExerciseResult', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_ExerciseResult_id', table_name='ExerciseResult')
    op.create_foreign_key(None, 'ExerciseResult', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ExerciseResult', type_='foreignkey')
    op.create_index('ix_ExerciseResult_id', 'ExerciseResult', ['id'], unique=False)
    op.drop_column('ExerciseResult', 'user_id')
    # ### end Alembic commands ###
